name = input("Enter your name: ")
surname = input("Enter your surname: ")
age = input("Enter your age: ")
num1 = input("Enter the first number: ")
num2 = input("Enter the second number: ")

print(type(name))
print(type(surname))
print(type(age))
print(type(num1))
print(type(num2))
